
{{- if .Values.pg.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "initdb.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "initdb.labels" . | indent 4 }}
  annotations:
{{- with .Values.secret.secretAnnotations }}
  {{- toYaml . | nindent 4 }}
{{- end }}
type: Opaque
stringData:
  PGHOST: {{ required "pg.host required" .Values.pg.host | quote }}
  PGPASSWORD: {{ .Values.pg.admin.password | quote }}
  PGUSER: {{ .Values.pg.admin.username | quote }}
  PGPORT: {{ .Values.pg.port | quote }}
  PGDATABASE: "postgres"
  USER: {{ include "initdb.username" . }}
  PASSWORD: {{ include "initdb.password" . }} 
  DBNAME: {{ required "A valid pg.target.databaseName is required!" .Values.pg.target.databaseName }}
{{- end }}